### ISSUE TITLE
Retrieving image

### ISSUE THREAD

**Issue by sarunl** [cslinmiso/LineAPI4J#1]
Hello Thanks for the lib

Is there any way to retrieve image from IMAGE type message?

**Comment by cslinmiso** [comment]
Hi, I will have to check it when I am free. 
Would you give me more information to look into it? e.g. you were running which method?
I will let you know.

**Comment by sarunl** [comment]
Hi thanks for reply,

in fetchOperations if the operation is send or receive, there is a contentPreview property in message. but it is always null.

you can take your time , no hurry.

cheers

**Comment by cslinmiso** [comment]
Hi @sarunl 
I've done some tests, found no problem with IMAGE type msg.
I was able to read the image file. Would you please try to pull the latest code so you could run the test again?
Thanks.
