### ISSUE TITLE
longPoll() method Operation that has OpType = OpType.RECEIVE_MESSAGE text is always null

### ISSUE THREAD

**Issue by ekbunditw** [cslinmiso/LineAPI4J#12]
Hi @cslinmiso
I got some problems when try to using longPoll() method.
File : LineClient.java
operation that get from fetchOperations() that have OpType.RECEIVE_MESSAGE got text is always null. 
I am not sure that happen only with me or with everyone. try investigating into it.
I would like to ask that you got this problem or it just happen to me only ? 
Cheers !

**Comment by cslinmiso** [comment]
Hi, glad you find it useful!
I am not sure why it will happen since i didn't test it much.
However, I found a possible related solution. 
https://github.com/carpedm20/LINE/issues/69

let me know if it helps.

**Comment by ekbunditw** [comment]
Hi @ruyaoyao 
thanks for your reply.
now it work ! thanks again 👍

**Comment by cslinmiso** [comment]
would you mind sharing how did you make it work?
Thanks!

**Comment by ekbunditw** [comment]
Hi again @ruyaoyao
After looking into link you provided me above.
Going into LINE Application settings and turn letter sealing off.
As its description says 
"Messages will be protected using advanced encrytion. **Letter Sealing will only work for chats where your friend has also enable it**" 
so i just turn it off on bot's side.
then bot can read any text from anyone.

Cheers !

**Comment by cslinmiso** [comment]
Great, thanks for sharing :)

**Comment by jackzett** [comment]
I have turned off letter sealinng too but it doesnt seem to fix it for me
Using carpedm20's line api i can log in successfully, select the user i want to interact with, and then getrecentmessages(count=20) wil give [ ] even though lettersealing is of on my bot's account on my phone

Any what else could have caused this?

**Comment by cslinmiso** [comment]
@jackzett it's the same problem that LINE has been updated their service. Still have no clue cracking it.

**Comment by jackzett** [comment]
@cslinmiso Ah okay that explains it, so far luckily the longpoll is still working
